---
require:
  - rubocop-performance

AllCops:
  DefaultFormatter: fuubar
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable

#################### Layout ###########################

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

#################### Style ###############################

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
