AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true

Rails:
  Enabled: true

#################### Style #################################

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

#################### Metrics ###############################

Metrics/LineLength:
  Exclude:
    - Gemfile
