---
AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Rails:
  Enabled: true

#################### Style #################################

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

#################### Metrics ###############################

Metrics/LineLength:
  Exclude:
    - Gemfile
