---
AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Rails:
  Enabled: true

#################### Layout ################################

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

#################### Style #################################

Style/ClassAndModuleChildren:
  AutoCorrect: true

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

#################### Metrics ###############################

Metrics/BlockLength:
  Exclude:
    - lib/tasks/auto_annotate_models.rake  # for annotate

Metrics/LineLength:
  Exclude:
    - Gemfile
    - Rakefile
    - config/application.rb
    - config/environments/**/*
    - config/initializers/**/*
    - config/puma.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

#################### Bundler ###############################

Bundler/OrderedGems:
  Enabled: false

#################### Rails #################################

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - edge
    - staging
    - production

#################### RSpec #################################
require: rubocop-rspec
