---
x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile
  tmpfs:
    - /tmp
    - /usr/src/app/tmp/pids
  volumes:
    - .:/usr/src/app
    - bundle-data:/usr/local/bundle
  stdin_open: true
  tty: true
  environment:
    EDITOR: vi
    RUBOCOP_OPTS: --server
    RUBYOPT: -W:deprecated
  depends_on:
    - db

services:
  db:
    image: postgres:14.5-alpine3.16
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    <<: *app
    command: bin/rails server --binding=0.0.0.0
    ports:
      - 3000:3000
  dev:
    <<: *app
    command: bin/spring server
    ports:
      - 35729:35729

volumes:
  db-data:
  bundle-data:
