---
version: '3.8'

services:
  db:
    image: postgres:14.5-alpine3.16
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app:cached
      - bundle-data:/usr/local/bundle:delegated
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      EDITOR: vi
  dev:
    <<: *app
    command: bundle exec spring server
    ports:
      - 35729:35729

volumes:
  db-data:
    driver: local
  bundle-data:
    driver: local
